[[redirects]]
  from = "/.well-known/acme-challenge/*"
  to = "/.well-known/acme-challenge/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://www.bigconfig.ai/:splat"
  status = 302
  force = true
